// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError('Unsupported platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyChEEzHGJNCu00i75l9TZH0Vb18-BNfukM",
    authDomain: "flutter-hayat.firebaseapp.com",
    projectId: "flutter-hayat",
    storageBucket: "flutter-hayat.appspot.com",
    messagingSenderId: "178045166210",
    appId: "1:178045166210:web:e54700a0b5ee7c49fa4a9b",
    measurementId: "G-38YLBVR39X",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyC34lp3Kd3RyaCbrCHnv4tVsjWhohkjc04', // from android current_key
    projectId: 'flutter-hayat',
    appId: '1:178045166210:android:6966b77e29628fa6fa4a9b',
    messagingSenderId: '123456789012',
    storageBucket: 'flutter-hayat.appspot.com', // optional
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVaZeQlIOWyMDquOdnDnlbnHbQpLYnXQ', // from iOS plist
    appId: '1:123456789012:ios:abcdef123456',
    messagingSenderId: '178045166210',
    projectId: 'flutter-hayat',
    storageBucket: 'flutter-hayat.appspot.com', // optional
    iosBundleId: 'com.whitelable.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSy…', // usually same as iOS
    appId: '1:123456789012:ios:abcdef123456',
    messagingSenderId: '123456789012',
    projectId: 'flutter-hayat',
    storageBucket: 'flutter-hayat.appspot.com',
    iosBundleId: 'com.whitelable.dev',
  );
}
