workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'  # Run pipeline on push

stages:
  - build
  - deploy

image: cirrusci/flutter:latest  # Use latest Flutter Docker image

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pub-cache/
    - build/web/

before_script:
  - flutter clean
  - flutter pub get

build_web:
  stage: build
  script:
    - flutter build web --release --base-href /$CI_PROJECT_NAME/
  artifacts:
    paths:
      - build/web
    expire_in: 1 week

deploy_gitlab_pages:
  stage: deploy
  script:
    - mv build/web public
  artifacts:
    paths:
      - public
  only:
    - main  # Deploy only from the main branch
