name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          flutter-version: '3.29.2'  # Specify your Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href /Flutter-White-Label/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          cname: example.com  # Optional: Replace with your custom domain if applicable
